New option to build non-core code as a static lib
MRtrix3/mrtrix3 pull request #2907
Opened 2024-05-15 12:18 UTC by daljit46

As mentioned in the meeting today, it'd make sense for production builds to have the C++ code in `src` built as a static library. This PR adds a new `MRTRIX_BUILD_STATIC` option to allow for this (@MRtrix3/mrtrix3-devs if anyone has a better name please let me know).
The option is disabled by default and is only intended to be enabled in production and external projects. For every day builds, making shared libraries provides a faster incremental build workflow.

2024-05-15 23:01 UTC, Lestropie requested changes
Seems a simple enough modifier to have in place regardless of whether it actually gets used for any end purpose.

Regarding the name, it probably needs to be clear that it's not *the entire build* that's static, only that outside of core, especially given earlier builds have had full static build capability (though from memory it's been a little patchy at times).

2024-05-16 10:16 UTC, daljit46 commented
> Regarding the name, it probably needs to be clear that it's not the entire build that's static, only that outside of core, especially given earlier builds have had full static build capability (though from memory it's been a little patchy at times).

Unfortunately, I don't have good ideas for the name (neither does ChatGPT). The best I could come up with is `MRTRIX_BUILD_NON_CORE_STATIC`.

2024-05-16 12:55 UTC, Lestropie commented
If ChatGPT can't even come up with variable names, is it even fit for purpose? I mean, that's 98% of the work to be done. 🤡  No clear superior alternative to `MRTRIX_BUILD_NON_CORE_STATIC` from me. Will take the slight clumsiness for the sake of accuracy.

2024-06-20 11:44 UTC, daljit46 commented
@Lestropie can we merge this?

2024-06-20 23:25 UTC, Lestropie approved these changes
I'm not very familiar with static builds so can't really feedback on the utility of the change, but as far as the change itself goes I see no issue with merging.

2024-06-20 23:25 UTC, merged